[package]
name = "frusty-logger"
version = "0.1.0"
authors = ["Sunshine Foundation Developers", "Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"
description = "A Bridge between Rust log crate and Flutter"

[dependencies]
log = "^0.4"
allo-isolate = "^0.1"
env_logger = "^0.7"
yansi = "^0.5"
chrono = "0.4.19"